
const DataList = [
    { genre: "Action & adventure", code: "1365", type: "Action & adventure" },
    { genre: "Action comedies", code: "43040", type: "Action & adventure" },
    { genre: "Action sf & fantasy", code: "1568", type: "Action & adventure" },
    { genre: "Action thrillers", code: "43048", type: "Action & adventure" },
    { genre: "Adventures", code: "7472", type: "Action & adventure" },
    { genre: "Asian action movies", code: "77232", type: "Action & adventure" },
    { genre: "Classic Action & Adventure", code: "46576", type: "Action & adventure" },
    { genre: "Comic book and superhero movies", code: "10118", type: "Action & adventure" },
    { genre: "Crime action & adventure", code: "9584", type: "Action & adventure" },
    { genre: "Foreign action & adventure", code: "11828", type: "Action & adventure" },
    { genre: "Hijacking movies", code: "05412", type: "Action & adventure" },
    { genre: "Martial arts movies", code: "8985", type: "Action & adventure" },
    { genre: "Military action & adventure", code: "2125", type: "Action & adventure" },
    { genre: "Spy action & adventure", code: "10702", type: "Action & adventure" },
    { genre: "Western", code: "7700", type: "Action & adventure" },

    { genre: "Anime", code: "7424", type: "Anime" },
    { genre: "Adult animation", code: "11881", type: "Anime" },
    { genre: "Animal tales", code: "5507", type: "Anime" },
    { genre: "Anime Sci-Fi", code: "2729", type: "Anime" },
    { genre: "Anime action", code: "2653", type: "Anime" },
    { genre: "Anime comedies", code: "9302", type: "Anime" },
    { genre: "Anime dramas", code: "452", type: "Anime" },
    { genre: "Anime dramas", code: "11146", type: "Anime" },
    { genre: "Anime features", code: "3063", type: "Anime" },
    { genre: "Anime horror", code: "10695", type: "Anime" },
    { genre: "Anime series", code: "6721", type: "Anime" },

    { genre: "Comedies", code: "6548", type: "Comedies" },
    { genre: "Animes comedies", code: "9302", type: "Comedies" },
    { genre: "Dark comedies", code: "869", type: "Comedies" },
    { genre: "Foreign Comedies", code: "4426", type: "Comedies" },
    { genre: "Horror comedies", code: "89585", type: "Comedies" },
    { genre: "Late Night Comedies", code: "1402", type: "Comedies" },
    { genre: "Mockumentaries", code: "26", type: "Comedies" },
    { genre: "Musicals comedies", code: "13335", type: "Comedies" },
    { genre: "Political comedies", code: "2700", type: "Comedies" },
    { genre: "Romantic Comedies", code: "5475", type: "Comedies" },
    { genre: "Satires", code: "4922", type: "Comedies" },
    { genre: "Screwball Comedies", code: "9702", type: "Comedies" },
    { genre: "Slapstick comedies", code: "10256", type: "Comedies" },
    { genre: "Sports comedies", code: "5286", type: "Comedies" },
    { genre: "Stand-up Comedy", code: "11559", type: "Comedies" },
    { genre: "Teen Comedies", code: "3519", type: "Comedies" },

    { genre: "Gay & Lesbian Dramas", code: "500", type: "LGBTQ" },
    { genre: "Gay & Lesbian TV Shows", code: "65263", type: "LGBTQ" },
    { genre: "Romantic Gay & Lesbian Movies", code: "3329", type: "LGBTQ" },
    { genre: "LGBTQ", code: "5977", type: "LGBTQ" },
    { genre: "Gay & Lesbian Comedies", code: "7120", type: "LGBTQ" },
    { genre: "Gay & Lesbian Documentaries", code: "4720", type: "LGBTQ" },
    
    { genre: "Independent movies", code: "7077", type: "Independent movies" },
    { genre: "Romantic independent movies", code: "9916", type: "Independent movies" },
    { genre: "Independent thrillers", code: "3269", type: "Independent movies" },
    { genre: "Independent dramas", code: "384", type: "Independent movies" },
    { genre: "Independent comedies", code: "4195", type: "Independent movies" },
    { genre: "Independent action & adventure", code: "11804", type: "Independent movies" },
    { genre: "Experimental movies", code: "11079", type: "Independent movies" },
 
    { genre: "Horror movies", code: "8711", type: "Horror movies" },
    { genre: "Zombie horror movies", code: "75405", type: "Horror movies" },
    { genre: "Werewolf horror movies", code: "75930", type: "Horror movies" },
    { genre: "Vampire horror movies", code: "75804", type: "Horror movies" },
    { genre: "Teen screams", code: "52147", type: "Horror movies" },
    { genre: "Supernatural horror movies", code: "42023", type: "Horror movies" },
    { genre: "Slasher and serial killer movies", code: "8646", type: "Horror movies" },
    { genre: "Satanic stories", code: "6998", type: "Horror movies" },
    { genre: "Monster movies", code: "947", type: "Horror movies" },
    { genre: "Horror comedy", code: "89585", type: "Horror movies" },
    { genre: "Foreign horror movies", code: "8654", type: "Horror movies" },
    { genre: "Deep sea horror movies", code: "45028", type: "Horror movies" },
    { genre: "Cult horror movies", code: "10944", type: "Horror movies" },

  ];

export default DataList;